// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo/config"
	"demo/hander/v1"
	"demo/serve"
)

// Injectors from wire.go:

func InitializeApp() *App {
	httpServer := serve.NewHttpServer()
	configConfig := config.NewConfig()
	helloHander := V1.NewHelloHander(httpServer)
	app := &App{
		Service: httpServer,
		config:  configConfig,
		v1:      helloHander,
	}
	return app
}

// wire.go:

type App struct {
	Service *serve.HttpServer
	config  *config.Config
	v1      *V1.HelloHander
}
