// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo/config"
	"demo/pkg/store"
)

// Injectors from wire.go:

func InitializeApp() *App {
	configConfig := config.NewConfig()
	mySQL := store.NewMySQL(configConfig)
	app := &App{
		db:     mySQL,
		config: configConfig,
	}
	return app
}

// wire.go:

type App struct {
	db     *store.MySQL
	config *config.Config
}
